### ISSUE TITLE
Can't open .mov file on Android

### ISSUE THREAD

**Issue by talltom** [matthewberryman/brunsviga#1]
* Samsung Motorola Moto 3
* Android 6

Clicking on the email link downloads the file. Clicking on the file in "downloads" returns error (from Android) "Can't open file".

**Comment by matthewberryman** [comment]
Ah, I forget there are non-Apple users sometimes. ;)
When I get AWS Elastic Transcoder going (on my todo list) it should handle this, in the interim I can upload to YouTube (although I would prefer to use AWS as a good demo on AWS services). I will leave this ticket open until I get transcoding working automatically.

**Comment by matthewberryman** [comment]
Fixed with d6bad86 (change to workflow for now).
